### ISSUE TITLE
Output directory is not deleted by default

### ISSUE THREAD

**Issue by AWhetter** [storax/jinjaapidoc#7]
https://github.com/storax/jinjaapidoc/blob/cf963dda17d25abe7503cd422839175006902899/docs/usage.rst states that `jinjaapi_nodelete` is set to `False` by default and that therefore the output directory is deleted by default.

This is not the case. Either the documentation needs to change or https://github.com/storax/jinjaapidoc/blob/1e05b7c9d76a4a7ac57c7454aa1ade4d6c3a6f0a/src/jinjaapidoc/__init__.py#L33 does.

**Comment by storax** [comment]
Thanks, I will look into it.

**Comment by storax** [comment]
You were right, the documentation was false. I don't want to delete the output directory by default for safety reasons.
Thanks for raising this ticket. I released a new patch (0.3.1) with the fixed documentation.
